sources:
  - name: ens
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${NEXT_PUBLIC_SUBGRAPH_API_KEY}/subgraphs/id/5XqPmWe6gjyrJtFn9cLy237i4cWw2j9HcUJEXsP5qGtH
    transforms:
      - autoPagination:
        validateSchema: true

documents:
  - ./src/graphql/*.graphql
